### ISSUE TITLE
app\Console\Kernal.php file must be renamed to Kernel.php

### ISSUE THREAD

**Issue by realmxsandr** [TBlindaruk/laravel-example-app#12]
Fatal error: Uncaught ReflectionException: Class App\Console\Kernel does not exist in /application/vendor/laravel/framework/src/Illuminate/Container/Container.php:767
Stack trace:
#0 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('App\\Console\\Ker...')
#1 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('App\\Console\\Ker...')
#2 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('App\\Console\\Ker...', Array)
#3 /application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('App\\Console\\Ker...', Array)
#4 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(256): Illuminate\Foundation\Application->make('App\\Console\\Ker...', Array)
#5 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(764): Illuminate\Co in /application/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767

**Comment by realmxsandr** [comment]
Fatal error: Uncaught ReflectionException: Class App\Console\Kernel does not exist in /application/vendor/laravel/framework/src/Illuminate/Container/Container.php:767
Stack trace:
#0 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('App\\Console\\Ker...')
#1 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('App\\Console\\Ker...')
#2 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('App\\Console\\Ker...', Array)
#3 /application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('App\\Console\\Ker...', Array)
#4 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(256): Illuminate\Foundation\Application->make('App\\Console\\Ker...', Array)
#5 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(764): Illuminate\Co in /application/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767
